### ISSUE TITLE
dropdown header  

### ISSUE THREAD

**Issue by JulioGroaz** [DanieleTrippodo/proj-html-vuejs#7]
creazione del dropdown header (menu a tendina)

**Comment by DanieleTrippodo** [comment]
vedo se trovo il tempo di darti una mano con i menù

**Comment by JulioGroaz** [comment]
Bella grazie, teoricamente ho creato un nuovo branch che si chiama
dropdown-header. Ho aggiunto li quello che ho fatto, manca l’hover sui
contenuti del menu a tendina e in realtà dato che ho usato un margin per
spostare il menù sotto l’header ora non rimane aperto.


Il giorno ven 21 giu 2024 alle 11:44 DDD ***@***.***> ha
scritto:

**Comment by DanieleTrippodo** [comment]
mmh il branch lo hai creato il locale molto probabilmente, perchè io non lo vedo...
però nessun problema posso sempre crearne uno io~
